layout_spectrum: 0.9222521
color:
  saturation: 0.5561529
  lightness: 0.6003584
  brandStrength: 0.4880525
  brandColors:
    - '#000000'
    - '#B4B4B4'
    - '#653A16'
    - '#777776'
    - '#F4F4F4'
  rhythmicContrast: 0.9109916
typography_spectrum: 0.541816
name: ADuckOnARock ProDucktions
