name: ADuckOnARock ProDucktions
favicon: null
layout_spectrum: 0.51984
typography_spectrum: 0.541816
title: ADuckOnARock ProDucktions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#B4B4B4'
    - '#653A16'
    - '#777776'
    - '#F4F4F4'
  brandStrength: 0.4880525
  lightness: 0.6003584
  saturation: 0.5561529
  rhythmicContrast: 0.9109916
purpose: []
